apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-complete
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/gidikoml/devops-complete.git
    targetRevision: main
    path: helm-chart

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true