name: devops-complete project CI/CD pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t arrovi18/devops-complete:${{ env.SHORT_SHA }} terraform-configs

      - name: Push Docker image
        run: docker push arrovi18/devops-complete:${{ env.SHORT_SHA }}

      - name: Show directory structure (debug)
        run: |
          echo "Current directory:"
          pwd
          echo "Root content:"
          ls
          echo "Full tree:"
          ls -R

      - name: Configure Git Author
        run: |
          git config --global user.name "gidikoml"
          git config --global user.email "aroyovo376@gmail.com"

      - name: Update Helm chart image tag (safe)
        shell: bash
        run: |
          FILE="helm-chart/values.yaml"

          if [ -f "$FILE" ]; then
            echo "Updating Helm chart image tag..."

            sed -i "s/tag: .*/tag: ${SHORT_SHA}/" "$FILE"

            git add "$FILE"
            git commit -m "Update image tag to ${SHORT_SHA}" || echo "No changes to commit"
            git push
          else
            echo "helm-chart/values.yaml NOT FOUND"
          fi
